Fix email layout
Etherna/etherna-sso pull request #71
Opened 2021-11-04 07:46 UTC by mattiaz9

2021-11-04 07:47 UTC, mattiaz9 commented
@tmm360 Images in emails point to the server so should be tested in a staging env

2021-11-04 19:04 UTC, tmm360 requested changes
Still seeing with layout issues on Outlook

2021-11-05 16:12 UTC, tmm360 requested changes
Bottom images doesn't load
![image](https://user-images.githubusercontent.com/7620704/140542646-a5bd5aad-cd52-4822-b17a-b9b4d4ef4ba7.png)

2021-11-06 11:37 UTC, tmm360 approved these changes

2021-11-06 11:37 UTC, merged